// Generated by gencpp from file wds_battery_msgs/WdsBattery.msg
// DO NOT EDIT!


#ifndef WDS_BATTERY_MSGS_MESSAGE_WDSBATTERY_H
#define WDS_BATTERY_MSGS_MESSAGE_WDSBATTERY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wds_battery_msgs
{
template <class ContainerAllocator>
struct WdsBattery_
{
  typedef WdsBattery_<ContainerAllocator> Type;

  WdsBattery_()
    : header()
    , voltage(0.0)
    , current(0.0)
    , charge(0.0)
    , capacity(0.0)
    , design_capacity(0.0)
    , percentage(0.0)
    , power_supply_status(0)  {
    }
  WdsBattery_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , voltage(0.0)
    , current(0.0)
    , charge(0.0)
    , capacity(0.0)
    , design_capacity(0.0)
    , percentage(0.0)
    , power_supply_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef float _current_type;
  _current_type current;

   typedef float _charge_type;
  _charge_type charge;

   typedef float _capacity_type;
  _capacity_type capacity;

   typedef float _design_capacity_type;
  _design_capacity_type design_capacity;

   typedef float _percentage_type;
  _percentage_type percentage;

   typedef uint8_t _power_supply_status_type;
  _power_supply_status_type power_supply_status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(POWER_SUPPLY_STATUS_UNKNOWN)
  #undef POWER_SUPPLY_STATUS_UNKNOWN
#endif
#if defined(_WIN32) && defined(POWER_SUPPLY_STATUS_CHARGING)
  #undef POWER_SUPPLY_STATUS_CHARGING
#endif
#if defined(_WIN32) && defined(POWER_SUPPLY_STATUS_DISCHARGING)
  #undef POWER_SUPPLY_STATUS_DISCHARGING
#endif
#if defined(_WIN32) && defined(POWER_SUPPLY_STATUS_NOT_CHARGING)
  #undef POWER_SUPPLY_STATUS_NOT_CHARGING
#endif
#if defined(_WIN32) && defined(POWER_SUPPLY_STATUS_FULL)
  #undef POWER_SUPPLY_STATUS_FULL
#endif

  enum {
    POWER_SUPPLY_STATUS_UNKNOWN = 0u,
    POWER_SUPPLY_STATUS_CHARGING = 1u,
    POWER_SUPPLY_STATUS_DISCHARGING = 2u,
    POWER_SUPPLY_STATUS_NOT_CHARGING = 3u,
    POWER_SUPPLY_STATUS_FULL = 4u,
  };


  typedef boost::shared_ptr< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> const> ConstPtr;

}; // struct WdsBattery_

typedef ::wds_battery_msgs::WdsBattery_<std::allocator<void> > WdsBattery;

typedef boost::shared_ptr< ::wds_battery_msgs::WdsBattery > WdsBatteryPtr;
typedef boost::shared_ptr< ::wds_battery_msgs::WdsBattery const> WdsBatteryConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wds_battery_msgs::WdsBattery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wds_battery_msgs::WdsBattery_<ContainerAllocator1> & lhs, const ::wds_battery_msgs::WdsBattery_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.voltage == rhs.voltage &&
    lhs.current == rhs.current &&
    lhs.charge == rhs.charge &&
    lhs.capacity == rhs.capacity &&
    lhs.design_capacity == rhs.design_capacity &&
    lhs.percentage == rhs.percentage &&
    lhs.power_supply_status == rhs.power_supply_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wds_battery_msgs::WdsBattery_<ContainerAllocator1> & lhs, const ::wds_battery_msgs::WdsBattery_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wds_battery_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4958115a128b6f8273fcd7ed62879d62";
  }

  static const char* value(const ::wds_battery_msgs::WdsBattery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4958115a128b6f82ULL;
  static const uint64_t static_value2 = 0x73fcd7ed62879d62ULL;
};

template<class ContainerAllocator>
struct DataType< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wds_battery_msgs/WdsBattery";
  }

  static const char* value(const ::wds_battery_msgs::WdsBattery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# WDS simplified battery status message\n"
"# Contains only essential battery metrics for drone monitoring\n"
"\n"
"std_msgs/Header header\n"
"  # uint32 seq        # Included in Header\n"
"  # time stamp        # Included in Header\n"
"  # string frame_id   # Included in Header\n"
"\n"
"float32 voltage             # Voltage in Volts (V)\n"
"float32 current             # Current in Amperes (A)\n"
"float32 charge              # Remaining charge in Ampere-hours (Ah)\n"
"float32 capacity            # Current battery capacity in Ampere-hours (Ah)\n"
"float32 design_capacity     # Design capacity in Ampere-hours (Ah)\n"
"float32 percentage          # Charge percentage (0-100)\n"
"uint8 power_supply_status   # Power supply status (constants from sensor_msgs/BatteryState)\n"
"\n"
"# Power supply status constants (matching sensor_msgs/BatteryState)\n"
"uint8 POWER_SUPPLY_STATUS_UNKNOWN = 0\n"
"uint8 POWER_SUPPLY_STATUS_CHARGING = 1\n"
"uint8 POWER_SUPPLY_STATUS_DISCHARGING = 2\n"
"uint8 POWER_SUPPLY_STATUS_NOT_CHARGING = 3\n"
"uint8 POWER_SUPPLY_STATUS_FULL = 4\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::wds_battery_msgs::WdsBattery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.voltage);
      stream.next(m.current);
      stream.next(m.charge);
      stream.next(m.capacity);
      stream.next(m.design_capacity);
      stream.next(m.percentage);
      stream.next(m.power_supply_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WdsBattery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wds_battery_msgs::WdsBattery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wds_battery_msgs::WdsBattery_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "current: ";
    Printer<float>::stream(s, indent + "  ", v.current);
    s << indent << "charge: ";
    Printer<float>::stream(s, indent + "  ", v.charge);
    s << indent << "capacity: ";
    Printer<float>::stream(s, indent + "  ", v.capacity);
    s << indent << "design_capacity: ";
    Printer<float>::stream(s, indent + "  ", v.design_capacity);
    s << indent << "percentage: ";
    Printer<float>::stream(s, indent + "  ", v.percentage);
    s << indent << "power_supply_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.power_supply_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WDS_BATTERY_MSGS_MESSAGE_WDSBATTERY_H
